import Foundation

/// The corpus-wide answer, in one place: across every captured disc, where
/// does the disc's own menu agree with the heuristic, where does it disagree,
/// and where does either abstain?
///
/// This is the artifact the user reads after a run of discs. It exists
/// because the question it answers — *is the menu's answer trustworthy
/// enough to ever preselect a title?* (`docs/menu-intelligence.md` §11
/// decision 4) — cannot be answered by one disc, and until now the evidence
/// for it was spread across five manifests and a corpus assertion that only
/// spoke when it failed.
///
/// **It decides nothing.** Reading this report is a human act. No code path
/// consumes it, and the answer it argues towards is still "no" until the
/// agree column has a lot more discs in it than the not-captured column.
nonisolated struct MenuAgreementReport: Equatable, Sendable {

    var rows: [MenuAgreement]

    /// Every caption seen anywhere in the corpus, with what the lexicon makes
    /// of it and which discs printed it. The `role == nil` rows are the work
    /// list: words a real disc prints that `MenuLexicon` has no row for.
    nonisolated struct Word: Equatable, Sendable, Comparable {
        var text: String
        var role: String?
        var discs: [String]

        static func < (lhs: Word, rhs: Word) -> Bool {
            (lhs.role ?? "~unknown", lhs.text) < (rhs.role ?? "~unknown", rhs.text)
        }
    }

    static func make(_ rows: [MenuAgreement]) -> MenuAgreementReport {
        MenuAgreementReport(rows: rows.sorted { $0.slug < $1.slug })
    }

    // MARK: - Counting

    func count(_ verdict: MenuAgreement.Verdict) -> Int {
        rows.filter { $0.verdict == verdict }.count
    }

    /// Discs where both sources named a title — the only rows that carry any
    /// information about trust. `agree + disagree`.
    var comparedDiscs: Int { count(.agree) + count(.disagree) }

    var disagreements: [MenuAgreement] { rows.filter { $0.verdict == .disagree } }

    /// The vocabulary, merged across discs.
    var vocabulary: [Word] {
        var merged: [String: Word] = [:]
        for row in rows {
            for label in row.signals.labels {
                if var existing = merged[label.text] {
                    if !existing.discs.contains(row.slug) { existing.discs.append(row.slug) }
                    merged[label.text] = existing
                } else {
                    merged[label.text] = Word(text: label.text, role: label.role, discs: [row.slug])
                }
            }
        }
        return merged.values.map { Word(text: $0.text, role: $0.role, discs: $0.discs.sorted()) }.sorted()
    }

    /// Words the lexicon does not know. Adding these as rows in
    /// `MenuLexicon.entries` is the whole maintenance loop.
    var unknownWords: [Word] { vocabulary.filter { $0.role == nil } }

    // MARK: - The text

    /// The committed artifact, `ChangeoverTests/Fixtures/discs/agreement-report.txt`.
    ///
    /// Deterministic: rows sorted by slug, words sorted by role then text,
    /// every number derived from the same pure functions the app runs. A
    /// capture that changes any of it changes this file, which is the point
    /// — the diff is the review.
    var text: String {
        var out: [String] = []
        out.append("Changeover — the disc menu against the title heuristic")
        out.append("=======================================================")
        out.append("")
        out.append("Generated by MenuAgreementReport over ChangeoverTests/Fixtures/discs/.")
        out.append("Regenerate with Tools/menu-agreement (see its header); the corpus sweep")
        out.append("fails if this file and the fixtures disagree.")
        out.append("")
        out.append("The heuristic decides what is encoded. Nothing below does, today or in")
        out.append("this pass: it is the evidence for whether the disc's own answer could")
        out.append("ever be trusted to preselect a title (menu-intelligence.md §11.4).")
        out.append("")
        out.append(summaryLine)
        out.append("")
        out.append(contentsOf: verdictTable)
        out.append("")
        out.append(contentsOf: signalTable)
        out.append("")
        out.append(contentsOf: vocabularySection)
        out.append("")
        out.append(contentsOf: readingSection)
        return out.joined(separator: "\n") + "\n"
    }

    var summaryLine: String {
        let parts = [
            "agree \(count(.agree))",
            "disagree \(count(.disagree))",
            "menu abstained \(count(.menuAbstained))",
            "heuristic abstained \(count(.heuristicAbstained))",
            "both abstained \(count(.bothAbstained))",
            "not captured \(count(.notCaptured))",
        ]
        return "\(rows.count) disc\(rows.count == 1 ? "" : "s"): " + parts.joined(separator: " · ")
    }

    private var verdictTable: [String] {
        var out = ["Verdicts", "--------"]
        let width = max(12, rows.map(\.slug.count).max() ?? 12)
        out.append(
            pad("disc", width) + "  " + pad("scanner", 12) + "  "
                + pad("heuristic", 24) + "  " + pad("disc menu", 34) + "  verdict"
        )
        for row in rows {
            out.append(
                pad(row.slug, width) + "  " + pad(Self.scannerText(row), 12) + "  "
                    + pad(Self.heuristicText(row), 24) + "  " + pad(Self.menuText(row), 34) + "  "
                    + row.verdict.rawValue
            )
        }
        return out
    }

    private var signalTable: [String] {
        var out = ["Signals", "-------"]
        let captured = rows.filter { $0.menuRoute != .notCaptured }
        guard !captured.isEmpty else {
            out.append("No disc in the corpus has a menus/ capture yet.")
            return out
        }
        for row in captured {
            let s = row.signals
            out.append("\(row.slug):")
            out.append("  menus \(s.menuCount) (\(s.menusWithButtons) with buttons), buttons \(s.buttonCount), busiest menu \(s.largestMenuButtons)")
            out.append("  title-jumping buttons \(s.titleJumpingButtons) → titles \(s.titlesJumpedTo.map(String.init).joined(separator: ","))")
            out.append("  chapter buttons \(s.chapterButtons) on \(s.chapterPages) page(s); names read \(s.chapterNamesRead), written \(s.chapterNamesEmitted)")
            out.append("  tv signal \(s.tvSignal.map { $0 ? "yes" : "no" } ?? "n/a") — \(s.tvSignalReason ?? "not evaluated")")
            out.append("  languages: spoken [\(s.spokenLanguages.joined(separator: ", "))] subtitles [\(s.subtitleLanguages.joined(separator: ", "))]")
            out.append("  button captions \(s.labels.count), unknown to the lexicon \(s.unknownLabels.count)")
        }
        return out
    }

    private var vocabularySection: [String] {
        var out = ["Button caption vocabulary (OCR'd off real discs)", "------------------------------------------------"]
        let words = vocabulary
        guard !words.isEmpty else {
            out.append("None: no captured disc has OCR attached to buttons yet.")
            return out
        }
        let width = max(20, words.map(\.text.count).max() ?? 20)
        for word in words {
            out.append(pad("\"\(word.text)\"", width + 2) + "  " + pad(word.role ?? "unknown", 12) + "  " + word.discs.joined(separator: ", "))
        }
        out.append("")
        if unknownWords.isEmpty {
            out.append("Every caption above is in MenuLexicon.entries.")
        } else {
            out.append("Unknown to MenuLexicon.entries — add a row per word, with its language,")
            out.append("what it does and the disc it was read off:")
            for word in unknownWords {
                out.append("  \"\(word.text)\"  (\(word.discs.joined(separator: ", ")))")
            }
        }
        return out
    }

    private var readingSection: [String] {
        var out = ["How to read this", "----------------"]
        out.append("\"not captured\" is absence of evidence, never disagreement: those discs")
        out.append("were archived before Tools/menudump existed and get their menus the next")
        out.append("time they pass through the drive.")
        out.append("")
        if comparedDiscs == 0 {
            out.append("No disc yet has both a menu answer and a heuristic answer, so this corpus")
            out.append("says nothing at all about whether the menu can be trusted.")
        } else {
            out.append("\(comparedDiscs) disc\(comparedDiscs == 1 ? " has" : "s have") an answer from both sources: \(count(.agree)) agree, \(count(.disagree)) disagree.")
            if disagreements.isEmpty {
                out.append("No disagreement so far. One-sided agreement on a handful of discs is not")
                out.append("evidence of a trustworthy rule — §11.4 stays \"no\" until the compared")
                out.append("column is large and still clean.")
            } else {
                out.append("Disagreements, which are the rows worth reading a disc back for:")
                for row in disagreements {
                    out.append("  \(row.slug): menu \(row.menuTitle.map(String.init) ?? "—") vs heuristic \(row.heuristicTitle.map(String.init) ?? "—") (\(row.heuristicRoute.rawValue))")
                }
            }
        }
        let playAll = rows.filter { $0.heuristicRoute == .playAllGuard }
        if !playAll.isEmpty {
            out.append("")
            out.append("Play All discs (\(playAll.map(\.slug).joined(separator: ", "))): the heuristic names a title and then")
            out.append("refuses it. A menu that points at the same title is agreeing about the")
            out.append("title, not about ripping it.")
        }
        return out
    }

    // MARK: - Cell text

    static func scannerText(_ row: MenuAgreement) -> String {
        if let title = row.scannerTitle { return "title \(title)" }
        guard let raw = row.scannerRaw else { return "absent" }
        return "none (\(raw))"
    }

    static func heuristicText(_ row: MenuAgreement) -> String {
        guard let title = row.heuristicTitle else { return "— (\(row.heuristicRoute.rawValue))" }
        return "title \(title) (\(row.heuristicRoute.rawValue))"
    }

    static func menuText(_ row: MenuAgreement) -> String {
        guard let title = row.menuTitle else { return "— (\(row.menuRoute.rawValue))" }
        let label = row.menuLabel.map { ", \"\($0)\"" } ?? ""
        return "title \(title) (\(row.menuRoute.rawValue)\(label))"
    }

    private func pad(_ text: String, _ width: Int) -> String {
        text.count >= width ? text : text + String(repeating: " ", count: width - text.count)
    }
}
